### ISSUE TITLE
Set a predefined list of possible values for string parameters

### ISSUE THREAD

**Issue by marcbal** [casiez/libparamtuner#9]
In the XML file, we could add an attribute for a string parameter that define a set of possible values.

In ParamTunerGUI, it will display a dropdown list instead of a textarea.

```xml
<myString type="string" value="BLACK" allowed="BLACK;WHITE;RED"/>
```

(maybe change "allowed" by an other mane, or change separator character if it's better)

We could also discuss about support of enum type, but this is not the final goal of this issue.

EDIT : 

A more XMLed solution
```xml
<myString type="string" value="BLACK">
	<value>BLACK</value>
	<value>WHITE</value>
	<value>RED</value>
</myString>
```

**Comment by casiez** [comment]
Yes that would be great. Someone suggested me that during the demo at IHM.
